### ISSUE TITLE
b站动态自动抽奖功能

### ISSUE THREAD

**Issue by someash** [yjqiang/bilibili-live-tools#101]
感觉这是一项很大的工程。。。如果大佬有兴趣的话，希望能有，不行就算了，天天抽小电视也不错
准备阶段，查询api与初步逻辑

*****************************
- [x] 动态获取，过滤抽奖动态
- [x] follow与unfollow，放在一个temp分组
- [x] 转发api
- [x] 详细逻辑，例如筛选、参与、删除
*****************
测试阶段
- [x] 数据库逻辑、自定义数据格式
- [x] 初级部分，即循环查找动态与初步过滤
- [x] 次级部分，即二次过滤与进行参与
- [x] 最后部分，即循环查看到期的动态，并处理后续
- [x] 测试验证
*****************
正式开发部分
- [x] 移植
- [x] 测试验证

**Comment by yjqiang** [comment]
工程不是很大 类似于实物抽奖流程  如果有时间的话 可否帮助抓一下包

**Comment by yjqiang** [comment]
准备阶段，查询api与初步逻辑
- [ ] 动态获取，过滤抽奖动态
- [ ] follow与unfollow，放在一个temp分组
- [ ] 转发api

测试阶段
- [ ] to be decided

**Comment by someash** [comment]
![qq 20181026203707](https://user-images.githubusercontent.com/32922655/47566659-faa3eb80-d95e-11e8-84ca-fb2fefe62fa4.png)
互动抽奖只显示了转发关注，看这个动态估计up会手动检查是否收藏，感觉如果功能做好后还要检测文字，附加额外功能

**Comment by yjqiang** [comment]
有对应api，不用你担心了

**Comment by someash** [comment]
大佬，圣诞/元旦快乐，偷偷问下进展如何

**Comment by yjqiang** [comment]
遇到一个棘手的问题，同时参加或删除的话，可能会出现类似于线程不安全的东西，所以暂时后放优先级，目前在做架构全面调整

**Comment by someash** [comment]
是做到2.0上吗

**Comment by yjqiang** [comment]
> 是做到2.0上吗

对
