### ISSUE TITLE
当前Fork项目用 systemd 启动后, 查看日志格式不对, 原项目没问题

### ISSUE THREAD

**Issue by imknown** [yjqiang/bilibili-live-tools#104]
**当前Fork项目** 用 `systemd` 启动后, 查看日志格式不对
**原项目 没问题**

---

启动
``` bash
systemctl start bilibili-live-tools
```

查看日志
``` bash
journalctl -fu bilibili-live-tools
```

疯狂输出:
![default](https://user-images.githubusercontent.com/5681447/46583459-5aa72080-ca8a-11e8-9669-e7b92edae4fb.jpg)

但是当前Fork 使用 `python3 run.py` 没问题

**Comment by yjqiang** [comment]
话说bilibili-live-helper是什么？这个本项目没有啊？

**Comment by imknown** [comment]
@yjqiang 啊 不好意思 纯手打的, 打错了, 是 `bilibili-live-tools`, 是我的 service 的名字... 但是确实输出了这些 `无效输入的` 日志.

**Comment by yjqiang** [comment]
不太熟悉这个东西  要不你用nohub之类的重新试试看？会不会是这些接口之间的问题 因为这个东西windows并没有问题

**Comment by imknown** [comment]
我暂时先切到 上游项目 了.. `nohup` 不太方便看日志. 有时间我也看看源码.

**Comment by Franinc** [comment]
nohup也是如此，输出日志到文件的话会在几十秒内产生十几M的文本
换screen吧
应该是在8月31号或之前的某几次更新后出现的，在那之前能用nohup

**Comment by DkWyatt** [comment]
最好直接把日志关了，我一天就把35g的盘填满了，然后mysql就挂了

**Comment by yjqiang** [comment]
这个还是开着吧

**Comment by yjqiang** [comment]
@imknown 不久之后我会尝试修复一下，到时候麻烦帮忙测试一下，有时间么？

**Comment by imknown** [comment]
@yjqiang 不敢用了.. 被封了好几次..

**Comment by yjqiang** [comment]
> @yjqiang 不敢用了.. 被封了好几次.. 上游代码有问题. 如果频繁调用接口, 返回失败的话, 最好停止一下. 不然很容易被封.

返回失败？是指什么失败？

**Comment by imknown** [comment]
@yjqiang
> https://github.com/Dawnnnnnn/bilibili-live-tools/issues/82
https://github.com/Dawnnnnnn/bilibili-live-tools/issues/99
https://github.com/Dawnnnnnn/bilibili-live-tools/issues/161

**Comment by yjqiang** [comment]
> @yjqiang 返回失败的话 → 返回了 "400 失败" 的数据.
> > https://github.com/Dawnnnnnn/bilibili-live-tools/issues/82
> https://github.com/Dawnnnnnn/bilibili-live-tools/issues/99
> https://github.com/Dawnnnnnn/bilibili-live-tools/issues/161

嗷  小黑屋吧

**Comment by yjqiang** [comment]
返回了400表示已经就是小黑屋了

**Comment by someash** [comment]
我已经很久没有小黑屋了，只是貌似在国外挂着的(小)号(未实名)只能抽到辣条，绝对抽不到其他东西;在国内的(大)号(已实名)自从得到一次小电视抱枕之后就再没看到过实物奖品了

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili2.0/issues/57#issuecomment-465398867
