### ISSUE TITLE
请问主站每日任务的4个是？

### ISSUE THREAD

**Issue by someash** [yjqiang/bilibili-live-tools#105]
是那个登陆、看视频、客户端分享和投币吗？

**Comment by yjqiang** [comment]
对

**Comment by someash** [comment]
还有个问题。。这是啥？
![screenshot_20181009-224354](https://user-images.githubusercontent.com/32922655/46677282-ea78d600-cc14-11e8-8414-7fc3b0714c5f.png)

**Comment by yjqiang** [comment]
网络出现波动可能导致出现这个提示 这里的提示是websockets弹幕的，正常情况下不用管，会自动重连。以及不要把不同问题发在同一个issue里面。
