### ISSUE TITLE
今天萌节，年度大会员按等级减价

### ISSUE THREAD

**Issue by someash** [yjqiang/bilibili-live-tools#106]
6级的话拿b币给自己投币一年甚至还能回本（自动给自己投b币，自动领取各种限定挂件是不是一个好的新功能方向？）
作者大大，开通大会员还会进入无法抽奖小黑屋吗？

**Comment by yjqiang** [comment]
小黑屋完全是看心情，没有什么证据表明vip就少进了。

**Comment by yjqiang** [comment]
限定挂件似乎是b站自己开api，没有规律可循吧。这样的就不能用脚本

**Comment by yjqiang** [comment]
投b币这里不清楚，下次issue不要同时问多个无联系的问题

**Comment by yjqiang** [comment]
各种突发性活动基本都没办法，b站用暂时性api，没必要做

**Comment by yjqiang** [comment]
b币投币之后看看
