### ISSUE TITLE
MAX retries exceeded with url:/code

### ISSUE THREAD

**Issue by rabbit2rabbit** [yjqiang/bilibili-live-tools#107]
![image](https://user-images.githubusercontent.com/42423154/46895282-4c9e3900-ceaa-11e8-98d3-fee1c9c2be75.png)

**Comment by yjqiang** [comment]
这是验证码服务器的问题，https://github.com/Dawnnnnnn/bilibili-live-tools/blob/master/bilibili.py#L60
使用了该处的服务器，vps拒绝访问或者其他问题
