### ISSUE TITLE
频繁403

### ISSUE THREAD

**Issue by 0baiye** [yjqiang/bilibili-live-tools#110]
频繁403

**Comment by yjqiang** [comment]
可能有什么操作反复请求了吧 暂时无解  之后看看怎么处理

**Comment by yjqiang** [comment]
ip暂时被判定ddos之类了  等几十分钟吧

**Comment by 1161677781** [comment]
关于检测到20倍节奏风暴，是延迟抽奖还是立刻抽奖？

**Comment by yjqiang** [comment]
请另开新的issue  报告问题

**Comment by line1114** [comment]
403一周了，不过经验、辣条还是能领

**Comment by YWNDE** [comment]
辣条是指抽奖还是签到

> 403一周了，不过经验、辣条还是能领

**Comment by line1114** [comment]
> 辣条是指抽奖还是签到
> 
> > 403一周了，不过经验，辣条还是能领

抽奖，开始以为403是我又被ban了，后来发现每天的辣条还是有很多

**Comment by yjqiang** [comment]
抽奖403？可否把具体信息给我看看

**Comment by line1114** [comment]
> 抽奖403？可否把具体信息给我看看

![20181023133428_119](https://user-images.githubusercontent.com/26250205/47337926-88b27480-d6c8-11e8-867c-e57384327e13.jpg)

**Comment by yjqiang** [comment]
你的版本太低了吧……  这不是代码bug 这个api我早就废除了

**Comment by line1114** [comment]
> 你的版本太低了吧…… 这不是代码bug 这个api我早就废除了

最新不是3.0么？自从出席403我没事就看看更新的

**Comment by yjqiang** [comment]
我早就不用了啊……你没更新

**Comment by line1114** [comment]
> 我早就不用了啊……你没更新

原来bat自动升级是最新的，感谢大佬答复。
