### ISSUE TITLE
关于检测到20倍节奏风暴，是延迟抽奖还是立刻抽奖？

### ISSUE THREAD

**Issue by YWNDE** [yjqiang/bilibili-live-tools#111]
_Originally posted by @YWNDE in https://github.com/yjqiang/bilibili-live-tools/issues/110#issuecomment-431382208_

**Comment by yjqiang** [comment]
没有延迟  一次性查看  你可以自己改  在raffle_handler里面  由于设计利益问题  不会提供相关细节
