### ISSUE TITLE
建议移除PIL

### ISSUE THREAD

**Issue by HolynnChen** [yjqiang/bilibili-live-tools#115]
手动输入验证码在目前情况中使用次数几乎为0，建议移除PIL库降低安装难度（安装PIL在部分linux系统上需要前置条件）

**Comment by yjqiang** [comment]
如果有人需要的话 怎么办呢？ import包在文件写在里面的操作应该没有吧……

**Comment by HolynnChen** [comment]
可以将import写在函数内，这样不会一import该文件就把PIL import上，避免绝大多数人的使用障碍，然后requirement里可以去掉PIL，readme里写明若需要手动输入可自行安装PIL
ps.PIL是大库，体积很庞大的

**Comment by yjqiang** [comment]
这样吧 判定platform 如果是非linux  那么就需要pillow

**Comment by HolynnChen** [comment]
还是写在函数内比较保险，同时效率也很高。考虑存在使用linux桌面的人

**Comment by yjqiang** [comment]
还是觉得import写在函数里面过骚，虽然我也写了 但是我这个可以轻松拿出来  pillow自定义的话 感觉还是太骚了

**Comment by yjqiang** [comment]
https://github.com/nir0s/distro
你试试这个能不能查出linux的桌面还是服务器版本

**Comment by HolynnChen** [comment]
这东西只支持linux和BSD，不适合放入req，而且这个似乎也查不出桌面。桌面有两种，一种是原生，一种是服务器型？后者肯定只是软件，查不出的

**Comment by yjqiang** [comment]
嗯 的确是  linux桌面和server应该不分家的

**Comment by yjqiang** [comment]
你帮我找找aiohttp的骚操作位置 我看看 膜拜一下

**Comment by yjqiang** [comment]
这么着  判定系统是否有安装pillow 如果有的话 就倒入  用户自己控制是否真正安全运行（如果你没有安装pillow却在后续硬要打印，那么会出问题）

**Comment by HolynnChen** [comment]
https://github.com/aio-libs/aiohttp/blob/master/aiohttp/web.py
手机不方便找，随便找找的。里面有个利用importlib引入的，与直接import类似。
你说的方法还是避免不了不使用的人不导入，只能做到从req中移除。如果你坚持已安装pillow的人一定要引入的话也行，反正对现在的人影响不大，对后来者没有影响。

**Comment by yjqiang** [comment]
先开着，看看后续有什么好点的办法吧

**Comment by someash** [comment]
我用的桌面是这个http://www.linuxode.net/2017/104.html
貌似就输入过一次验证码（还是在win10上输入的，vps上貌似没输入过），后来就没见过手动输入验证码了

**Comment by lovezm** [comment]
![image](https://user-images.githubusercontent.com/10624938/49564543-e04a2e00-f95e-11e8-9076-7a13fa66318d.png)
话说这个是为啥

**Comment by yjqiang** [comment]
@lovezm 请另开issue

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili2.0/commit/155c420d6aac936911e9bb242daa047f97e965c5
