### ISSUE TITLE
403

### ISSUE THREAD

**Issue by YWNDE** [yjqiang/bilibili-live-tools#117]
403应该是同一时间内发送请求过于频繁吧？如果遇到一个人同时刷十几个以上礼物的话，能不能分段时间抽，而不是延迟60s后同一时间抽？

**Comment by yjqiang** [comment]
对的 可以这么做

**Comment by YWNDE** [comment]
可是就像今晚那样我感觉很难处理啊。。。

**Comment by YWNDE** [comment]
还有我觉得可以添加一个检测到403，软件停止30~60min，然后继续运行的功能

**Comment by yjqiang** [comment]
打算后续加入流量控制  限制最高并发

**Comment by yjqiang** [comment]
duplicated
