### ISSUE TITLE
请教下问题

### ISSUE THREAD

**Issue by rabbit2rabbit** [yjqiang/bilibili-live-tools#119]
类YJmonitorhandler下的handle_danmu函数中的参数body,是来自哪个函数的？是read_datas的吗？
我在改动的时候出现body这个参数没有decode方法的错误提示。‘’dict object has no attribute decode"。挠了半天的头

**Comment by yjqiang** [comment]
这是继承呀……继承了BaseDanmu里面的handle_danmu并覆盖其，所以body也是来自BaseDanmu里的read_datas的调用

**Comment by yjqiang** [comment]
> 这是继承呀……继承了BaseDanmu里面的handle_danmu并覆盖其，所以body也是来自BaseDanmu里的read_datas的调用，之前body的decode我是放在了read_datas里面，后来就挪出来了

我他妈脑子当时怎么想的来着？好像是和c搞混了，以为是值传值……

**Comment by rabbit2rabbit** [comment]
messages = remain_data.decode('utf-8')
                    dic = json.loads(messages)

看到以前的版本了，我自己写的时候，用remain_data.decode()也还是出现错误，

**Comment by yjqiang** [comment]
看意义肯定是你的remain_data格式不对，成了dict

**Comment by rabbit2rabbit** [comment]
f''放在Yj下的handle_danmu函数第一行有用吗？

其次，我看你的f'{{"uid":0,"roomid":{room_id},"protover":1,"platform":"web","clientver":"1.3.3"}}'不理解这个，为什么是两个花括号？

**Comment by yjqiang** [comment]
> f''放在Yj下的handle_danmu函数第一行有用吗？
> 
> 其次，我看你的f'{{"uid":0,"roomid":{room_id},"protover":1,"platform":"web","clientver":"1.3.3"}}'不理解这个，为什么是两个花括号？

这是f-string，是python3.6特性
