### ISSUE TITLE
服务器运行ssl报错

### ISSUE THREAD

**Issue by lovezm** [yjqiang/bilibili-live-tools#120]
![image](https://user-images.githubusercontent.com/10624938/49566181-be53aa00-f964-11e8-98ea-c3853b2d93b3.png)

**Comment by lovezm** [comment]
试着把verify_ssl=False这下更不行了=。=

**Comment by lovezm** [comment]
@yjqiang

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili2.0/issues/3
