### ISSUE TITLE
大航海  code：400 

### ISSUE THREAD

**Issue by scott90578** [yjqiang/bilibili-live-tools#121]
[2018-12-09 11:16:37] 0号弹幕监控检测到 6108362 的大航海(id: 638135)
{'code': 400, 'msg': '访问被拒绝', 'message': '访问被拒绝', 'data': []}
![tim 20181209112829](https://user-images.githubusercontent.com/24499006/49693134-930bcd80-fba5-11e8-9595-ba47fb9e85cb.png)

**Comment by yjqiang** [comment]
应该是进了小黑屋，大航海早就有小黑屋了

**Comment by yjqiang** [comment]
查看了一下  400的确是小黑屋普遍逻辑code 所以不是代码bug  是b站小黑屋
