### ISSUE TITLE
token失败 api错误 code -3

### ISSUE THREAD

**Issue by ma823478550** [yjqiang/bilibili-live-tools#122]
![image](https://user-images.githubusercontent.com/39283232/50048459-a923fd00-0081-11e9-8e37-404c83ba8759.png)

**Comment by yjqiang** [comment]
> ![image](https://user-images.githubusercontent.com/39283232/50048459-a923fd00-0081-11e9-8e37-404c83ba8759.png)
> 

这里逻辑没有考虑碰到验证码的情况，这是出来了验证码。没办法，可以去网页上验证一下，再重启脚本
