### ISSUE TITLE
任意门不发送弹幕公告了

### ISSUE THREAD

**Issue by rabbit2rabbit** [yjqiang/bilibili-live-tools#124]
任意门抽奖的公告变成飘屏了， 没有出现在弹幕池里面，所以检测不到

**Comment by yjqiang** [comment]
> 任意门抽奖的公告变成飘屏了， 没有出现在弹幕池里面，所以检测不到

有办法得到么？是需要改弹幕类型还是需要用其他api得到通知呢？

**Comment by yjqiang** [comment]
以及什么是飘屏？刚出的玩意儿么？

**Comment by rabbit2rabbit** [comment]
就是20倍节奏的那个飘屏……sys的

**Comment by yjqiang** [comment]
那还是弹幕  我看看  开了监控了

**Comment by yjqiang** [comment]
{'cmd': 'NOTICE_MSG', 'full': {'head_icon': 'http://i0.hdslb.com/bfs/live/a3e164513bd030f1113a8fbe1165454880c3ee4c.webp', 'tail_icon': 'http://i0.hdslb.com/bfs/live/822da481fdaba986d738db5d8fd469ffa95a8fa1.webp', 'head_icon_fa': 'http://i0.hdslb.com/bfs/live/28c2f3dd68170391d173ca2efd02bdabc917df26.png', 'tail_icon_fa': 'http://i0.hdslb.com/bfs/live/38cb2a9f1209b16c0f15162b0b553e3b28d9f16f.png', 'head_icon_fan': 1, 'tail_icon_fan': 4, 'background': '#8675F5FF', 'color': '#FFFFFFFF', 'highlight': '#FDFF2FFF', 'time': 20}, 'half': {'head_icon': 'http://i0.hdslb.com/bfs/live/df00be5ee88c4cd53514090a58f8702368b9a324.png', 'tail_icon': '', 'background': '#9299F2FF', 'color': '#FFFFFFFF', 'highlight': '#FDFF2FFF', 'time': 15}, 'side': {'head_icon': '', 'background': '', 'color': '', 'highlight': '', 'border': ''}, 'roomid': 4634937, 'real_roomid': 4634937, 'msg_common': '全区广播：主播<%红莉栖魔王喵%>开启了“任意门”，点击前往TA的房间去抽奖吧！', 'msg_self': '全区广播：主播<%红莉栖魔王喵%>开启了“任意门”，快来抽奖吧！', 'link_url': 'http://live.bilibili.com/4634937?live_lottery_type=1&broadcast_type=0&from=28003&extra_jump_from=28003', 'msg_type': 8, 'shield_uid': -1}
