### ISSUE TITLE
验证码服务器挂了

### ISSUE THREAD

**Issue by wacky6** [yjqiang/bilibili-live-tools#127]
```
HTTPConnectionPool(host='47.95.255.188', port=5000): Max retries exceeded with url: /code 

(Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb85771d588>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

---

这个的似乎能用 https://github.com/Hsury/Bilibili-Toolkit/blob/master/bilibili.py#L204
接口看起来变了。

---

另外，能不能提供一下验证码的模型，这样可以部署在自己机子上。（配合环境变量重新指定验证码服务的url）

**Comment by wacky6** [comment]
做了一个 telegram 手打验证码的实现。废掉 cnn_captcha 和 PIL/Pillow 。

适用服务器 headless 部署 https://github.com/wacky6/bilibili-live-tools/commit/385ee2b87ca110b69145fd93a323352c2dd973af

**Comment by yjqiang** [comment]
> ```
> HTTPConnectionPool(host='47.95.255.188', port=5000): Max retries exceeded with url: /code 
> 
> (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb85771d588>: Failed to establish a new connection: [Errno 111] Connection refused',))
> ```
> 
> ---
> 
> 这个的似乎能用 https://github.com/Hsury/Bilibili-Toolkit/blob/master/bilibili.py#L204
> 接口看起来变了。
> 
> ---
> 
> 另外，能不能提供一下验证码的模型，这样可以部署在自己机子上。（配合环境变量重新指定验证码服务的url）

服务器是原分支作者的。你可以问问他https://github.com/Dawnnnnnn/bilibili-live-tools

**Comment by yjqiang** [comment]
> 做了一个 telegram 手打验证码的实现。废掉 cnn_captcha 和 PIL/Pillow 。
> 
> 适用服务器 headless 部署 [wacky6@92c0a12](https://github.com/wacky6/bilibili-live-tools/commit/92c0a121b6526caf2745229acdc9030632800936)

这个东西估计不久就没了，现在滑动验证了，所以我不怎么打算改了
