### ISSUE TITLE
抽奖问题

### ISSUE THREAD

**Issue by yjqiang** [yjqiang/bilibili-live-tools#2]
2018-03-25 01:21:39 检测到房间   67336   的活动抽奖
出现了这种孤零零的行为，没有加入抽奖的提示，房间存在，怀疑是钓鱼？or bug

**Comment by yjqiang** [comment]
有人出现了活动抽奖结果 你的手速太快啦，再试试吧

**Comment by lovelyyoshino** [comment]
今天的宝箱好像出了问题

**Comment by yjqiang** [comment]
今凌晨的抽奖 我的正常啊

**Comment by yjqiang** [comment]
呸 宝箱 正常啊？

**Comment by Muromi-Rikka** [comment]
参与了房间 821119  的小电视抽奖
小电视道具抽奖状态: 访问被拒绝
{'code': 400, 'msg': '访问被拒绝', 'message': '访问被拒绝', 'data': {}}

**Comment by yjqiang** [comment]
@Muromi-Rikka  新的api启用了 应该解决了

**Comment by Muromi-Rikka** [comment]
刚刚clone新版本了试试看

**Comment by Muromi-Rikka** [comment]
[2018-05-08 22:13:51] 检测到房间 5311231 的小电视抽奖
[2018-05-08 22:13:56] 参与了房间 5311231 的小电视抽奖
# 小电视道具抽奖状态: OK
应该是正常了

**Comment by yjqiang** [comment]
其实这是小黑屋了。。。

**Comment by Muromi-Rikka** [comment]
好吧，不过没看到通知

**Comment by yjqiang** [comment]
解决了 多开了mmp

**Comment by Muromi-Rikka** [comment]
刚才尝试用alpine运行，结果pillow的安装给难到了，考虑出一个dockerfile么

**Comment by yjqiang** [comment]
不会……不打算做 因为pip都是很简单的

**Comment by Muromi-Rikka** [comment]
姑且还是做出来了，https://github.com/Muromi-Rikka/bilibili-live-tools-docker
