### ISSUE TITLE
关于实物抽奖

### ISSUE THREAD

**Issue by someash** [yjqiang/bilibili-live-tools#54]
并不是问编程相关，就是问问。。
这个实物抽奖是啥子，b站动态里面的抽奖？
还是别的什么。。。

*****************
### 设计
- [x] 相关api的查询与使用
- [x] 逻辑设计

### 测试
- [x] 写
- [x] 测

### 开发
--------------
- [x] 写
- [x] 测试

**Comment by someash** [comment]
顺便，这个实物抽奖一直在提示 已抽过。。

**Comment by yjqiang** [comment]
https://link.bilibili.com/p/center/index?/user-center/my-info/award#/user-center/my-info/award

**Comment by YWNDE** [comment]
实物抽奖能否做到自动检测+参与呢，而不是通过命令行来执行

**Comment by yjqiang** [comment]
可以，但是这里判定这里有些问题，我打算把它与动态抽奖合并
