### ISSUE TITLE
出现了断签

### ISSUE THREAD

**Issue by Outzzz** [yjqiang/bilibili-live-tools#55]
这几天礼物抽奖都是正常在进行，主站任务也是，但是直播就断签了

**Comment by someash** [comment]
后排问个问题，大佬能加个每日自动把瓜子换成硬币的功能么

**Comment by yjqiang** [comment]
silver2coin = false  user里面自行设置   断签问题暂时不清楚原因  持续跟踪

**Comment by yjqiang** [comment]
以及无关问题请不要堆积在同一个issue下面

**Comment by yjqiang** [comment]
应该修复了
