### ISSUE TITLE
挂机脚本的显示问题

### ISSUE THREAD

**Issue by someash** [yjqiang/bilibili-live-tools#62]
![qq 20180704075128](https://user-images.githubusercontent.com/32922655/42249683-38bb2442-7f5f-11e8-9d3a-cc82a6f8cf38.png)
看得头皮发麻。。。能不能让不必要的不显示

**Comment by yjqiang** [comment]
这里是辅助显示的，目的是想找到断签的原因……忍忍吧 找到了就删除
