### ISSUE TITLE
多勋章投递出现参数错误

### ISSUE THREAD

**Issue by lc4t** [yjqiang/bilibili-live-tools#63]
正在投递勋章
错误 参数错误(480)
错误 参数错误(480)
送出礼物: 亿圆X50
对xx共送出亲密度为500的礼物
错误 参数错误(480)
[2018-07-05 01:06:27] auto_send_gift
[2018-07-05 01:06:27] timeout

**Comment by yjqiang** [comment]
基本确定是b站api错误，现在不会出现了。
