### ISSUE TITLE
这个是啥。。我是被制裁了么

### ISSUE THREAD

**Issue by someash** [yjqiang/bilibili-live-tools#64]
![qq 20180706000117](https://user-images.githubusercontent.com/32922655/42334452-db671952-80af-11e8-90f0-a2384191fd1d.png)

**Comment by yjqiang** [comment]
今天似乎很多人进了……或者有可能一直在 只不过之前v4可以绕过现在不能绕了罢了

**Comment by someash** [comment]
如何解决它。。。。。

**Comment by yjqiang** [comment]
无法
