### ISSUE TITLE
需要图形桌面？

### ISSUE THREAD

**Issue by anglesgirl** [yjqiang/bilibili-live-tools#66]
单纯的纯命令行不能运行吗

**Comment by yjqiang** [comment]
可以啊

**Comment by yjqiang** [comment]
里面有个pillow 你删了吧 如果要图形要求  那个没什么必要的

**Comment by anglesgirl** [comment]
运行不了啊

[root@yageys bilibili]# python run.py
Traceback (most recent call last):
  File "run.py", line 18, in <module>
    bilibili()
  File "/root/bilibili/bilibili.py", line 31, in __new__
    cls.instance.dic_bilibili = configloader.load_bilibili(file_bilibili)
  File "/root/bilibili/configloader.py", line 27, in load_bilibili
    username = input("# \u8f93\u5165\u5e10\u53f7: ")
UnicodeEncodeError: 'ascii' codec can't encode characters in position 2-5: ordinal not in range(128)
[root@yageys bilibili]# python main.py
start OK!
Traceback (most recent call last):
  File "run.py", line 18, in <module>
    bilibili()
  File "/root/bilibili/bilibili.py", line 31, in __new__
    cls.instance.dic_bilibili = configloader.load_bilibili(file_bilibili)
  File "/root/bilibili/configloader.py", line 27, in load_bilibili
    username = input("# \u8f93\u5165\u5e10\u53f7: ")
UnicodeEncodeError: 'ascii' codec can't encode characters in position 2-5: ordinal not in range(128)

**Comment by anglesgirl** [comment]
[root@yageys bilibili]# python run.py
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    import OnlineHeart
  File "/root/bilibili/OnlineHeart.py", line 1, in <module>
    from bilibili import bilibili
  File "/root/bilibili/bilibili.py", line 3, in <module>
    from configloader import ConfigLoader
  File "/root/bilibili/configloader.py", line 2, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[root@yageys bilibili]#

**Comment by yjqiang** [comment]
需要调成utf 8，以及你没有安装toml包

**Comment by yjqiang** [comment]
utf8这破玩意儿有人试过，反正他没弄明白，建议windows使用，linux下面你得自己折腾

**Comment by anglesgirl** [comment]
终于运行成功
怎么样多账号运行呢
又如何后台挂机呢

**Comment by anglesgirl** [comment]
wget -N --no-check-certificate https://raw.githubusercontent.com/FunctionClub/LocaleCN/master/LocaleCN.sh && bash LocaleCN.sh

一键中文
千影基佬的

**Comment by yjqiang** [comment]
多账号的在写  目前只能多开了

**Comment by anglesgirl** [comment]
最后加上后台运行功能 最好有web配置 我先多开挂上另一个

**Comment by anglesgirl** [comment]
如果制作了后台运行
想必会需要用到通知功能

在这里推荐两个通知程序
Server酱	https://sc.ftqq.com/ 微信通知 每天300条
TelegramBot	https://core.telegram.org/bots/api  telegram通知 无限次
使用方法也很简单

# Server酱
# 自行替换 <SCKEY>
APP_CALLBACK="https://sc.ftqq.com/<SCKEY>.send?text={message}"

# TelegramBot
# 自行替换 <TOKEN> <CHAR_ID>
APP_CALLBACK="https://api.telegram.org/bot<TOKEN>/sendMessage?chat_id=<CHAR_ID>&text={message}"

**Comment by anglesgirl** [comment]
还有过滤文字啊  那就官方自己看吧

**Comment by yjqiang** [comment]
感谢

**Comment by yjqiang** [comment]
@anglesgirl  已经完成多用户

**Comment by anglesgirl** [comment]
多用户怎么使用

**Comment by anglesgirl** [comment]
最多几个账号 直接复制 那个无限添加吗

**Comment by yjqiang** [comment]
有人开了几百 正常运行 无限复制

**Comment by anglesgirl** [comment]
搞定了
