### ISSUE TITLE
提示弹幕姬连接不上

### ISSUE THREAD

**Issue by lovelyyoshino** [yjqiang/bilibili-live-tools#69]
# 正在启动直播监控弹幕姬
# 连接无法建立，请检查本地网络状况
<class 'TypeError'> cannot 'yield from' a coroutine object in a non-coroutine generator
在3.6的没有问题，是否是编写的协程问题

**Comment by yjqiang** [comment]
python 3.7 websocksetsb包问题

**Comment by yjqiang** [comment]
websockets最新版已经发布，可以正常使用
