### ISSUE TITLE
经过测试，在进小黑屋后，能够通过持续重复访问获得礼物

### ISSUE THREAD

**Issue by lovelyyoshino** [yjqiang/bilibili-live-tools#70]
可以在判定在进入小黑屋后持续请求获得礼物

**Comment by dust0517** [comment]
虽然说确实这个方法已经确认有效，但是该方法同时也会造成服务器的负载情况以及账号自身的问题，经过同某站研发的交流来看，不是特别推荐是用这种方式强行获取礼物，请谨慎对待您的账号。

**Comment by yjqiang** [comment]
@lovelyyoshino 由于403问题，暂时无解
