### ISSUE TITLE
应该还是露抽

### ISSUE THREAD

**Issue by yswcdmm** [yjqiang/bilibili-live-tools#71]
![louchou](https://user-images.githubusercontent.com/34054640/43180415-98150b90-900a-11e8-8f5b-5b0489769308.png)

**Comment by yjqiang** [comment]
之前更新做了摩天大楼的处理，但是发现c位这里也会露，目前不清楚原因

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bilibili-live-tools/commit/1e9d3f5edb27baa1261e7254289810fdea3a2ada
引入了新的机制
