### ISSUE TITLE
获取不到仲裁案件

### ISSUE THREAD

**Issue by Love4Taylor** [yjqiang/bilibili-live-tools#73]
在网页端可以仲裁, 并且昨天脚本还可以获取今天不行了

```
本次未获取到案件
[2018-07-27 08:58:02] [2018-07-27 08:58:02] 风纪委员会共获取0件案例，其中有效投票0件
```

**Comment by yjqiang** [comment]
b站有时一下子拉取不了20个，可能一次拉个4个，就停了，然后过一段时间又有

**Comment by Love4Taylor** [comment]
@yjqiang csrf 校验失败
![](https://wx3.sinaimg.cn/large/af997d39gy1fto6gad34ij211y0lc0wd.jpg)

**Comment by yjqiang** [comment]
已经修复，感谢反馈
