### ISSUE TITLE
请问Linux有后台python脚本的工具吗？

### ISSUE THREAD

**Issue by SGlace** [yjqiang/bilibili-live-tools#74]
大神，你好！请问类似于pm2的工具，有能将python脚本开机后台自启的工具吗？百度了nohup，screen都不能，萌新想求助大神

**Comment by yjqiang** [comment]
https://www.cnblogs.com/master-pokemon/p/5790783.html

**Comment by Love4Taylor** [comment]
supervisor
systemd
都可以

**Comment by SGlace** [comment]
@yjqiang @Love4Taylor 谢谢
