### ISSUE TITLE
运行后闪退

### ISSUE THREAD

**Issue by freeqbar** [yjqiang/bilibili-live-tools#75]
![qq 20180728152118](https://user-images.githubusercontent.com/37316724/43354402-a4d56a0c-927e-11e8-996b-6cd9733449bc.jpg)
python和依赖包都已经安装，运行后出现这个提示，之后程序自动关闭

**Comment by yjqiang** [comment]
你的user.toml应该改错了，把它贴上来

**Comment by freeqbar** [comment]
`[platform]
platform = "others"

[print_control]
danmu = false

[task_control]
# 清理即将过期礼物，请true之后一定要把紧随其后的room设置为真实房间号
clean-expiring-gift = true
# 单位秒
set-expiring-time = 43200
# 对过期礼物是否先投递到其他勋章(按照勋章等级投递)，之后会剩余的清理掉roomid里面
clean_expiring_gift2all_medal = false
clean-expiring-gift2room = 3442358

silver2coin = true

# 自动投满佩戴勋章当日亲密度
send2wearing-medal = false
# 房间号 短房间 
send2medal = []

# 老接口兑换硬币为银瓜子
doublegain_coin2silver = false

# 输入数字 0-5 表示主站自动投币
givecoin = 5
# 投币av获取(bilitop或者uper)分别代表b站随机或者根据up主mid选取
fetchrule = "uper"
# up主list([123]或者[123, 234, 123]等)
mid = [168598, 673816]


[other_control]
# 保持连接状态，下次再登陆不会重复登陆，读取存储的cookie重用，如要密码登陆，请手动清除bilibili.conf里面的cookie
keep-login = true

# 默认监听房间号
default_monitor_roomid = 3442358
`

**Comment by yjqiang** [comment]
没看出来，你不要对原来user.toml文件做任何改动，下载覆盖掉你目前的user，看看如何。本地不可能有问题的

**Comment by freeqbar** [comment]
覆盖之后重新修改了一次，可以正常运行了
![qq 20180728163743](https://user-images.githubusercontent.com/37316724/43354770-b32d3944-9284-11e8-9170-c117ffd8613b.jpg)
不过可能因为我是在云服务器上运行的，异地登陆B站需要手机验证，无法登陆

**Comment by yjqiang** [comment]
你可以在本机登陆，把cookie等信息复制到vps上
