### ISSUE TITLE
启动脚本时候有概率缺少一个房间的监听,重开脚本恢复正常.

### ISSUE THREAD

**Issue by 2314933036** [yjqiang/bilibili-live-tools#77]
![0w8uh5 6wi 4 vt8 t acn](https://user-images.githubusercontent.com/38069007/43365208-b2c616ec-935b-11e8-9481-db0248557160.jpg)
![qqglko gnuxu7fb9 h8u_8](https://user-images.githubusercontent.com/38069007/43365211-b4a6ff30-935b-11e8-9034-b9a6ec0277f9.jpg)

**Comment by yjqiang** [comment]
初步确定是connect建立时没有timeout。。。
