### ISSUE TITLE
关于风纪投票弃权率的问题

### ISSUE THREAD

**Issue by Love4Taylor** [yjqiang/bilibili-live-tools#79]
30 日的投票在凌晨 1 点 到 3 点之间全部完成, 但只有 3 个有效投票其他全部弃权. 是因为当时的投票人数不够?
建议凌晨推迟投票, 或者给用户提供投票频率/时间段设置.

**Comment by yjqiang** [comment]
不一定 我八点爬起来 有时也这样

**Comment by yjqiang** [comment]
目前无法确定b站推送机制

**Comment by yjqiang** [comment]
已经解决
