### ISSUE TITLE
自动投满佩戴勋章当日亲密度 功能失效

### ISSUE THREAD

**Issue by a253208088** [yjqiang/bilibili-live-tools#81]
Task exception was never retrieved
future: <Task finished coro=<auto_send_gift() done, defined at E:\bilibili-live-tools-master\Tasks.py:97> exception=KeyError('roomid',)>
Traceback (most recent call last):
  File "E:\bilibili-live-tools-master\Tasks.py", line 107, in auto_send_gift
    list_medal += await utils.fetch_medal(False, ConfigLoader().dic_user['task_control']['send2medal'])
  File "E:\bilibili-live-tools-master\utils.py", line 79, in fetch_medal
    list_medal.append((i['roomid'], int(i['dayLimit']) - int(i['todayFeed']), i['medal_name'], i['level']))
KeyError: 'roomid'

**Comment by yjqiang** [comment]
你修改一下roomid这里，把json打印出来，看看结果。正常来说，这不会出问题的

**Comment by yjqiang** [comment]
或者你看看你的勋章有没有异常的，比如主播被封之类的。

**Comment by a253208088** [comment]
怎么修改roomid,和打印JSON啊,
主播没被封,手动投没问题

**Comment by yjqiang** [comment]
```
async def fetch_medal(show=True, list_wanted_medal=[]):
    printlist = []
    list_medal = []
    if show:
        printlist.append('查询勋章信息')
        printlist.append(
            '{} {} {:^12} {:^10} {} {:^6} {}'.format(adjust_for_chinese('勋章'), adjust_for_chinese('主播昵称'), '亲密度',
                                                   '今日的亲密度', adjust_for_chinese('排名'), '勋章状态', '房间号码'))
    dic_worn = {'1': '正在佩戴', '0': '待机状态'}
    json_response = await bilibili.request_fetchmedal()
    print(json_response)
    if not json_response['code']:
        for i in json_response['data']['fansMedalList']:
            list_medal.append((i['roomid'], int(i['dayLimit']) - int(i['todayFeed']), i['medal_name'], i['level']))
            if show:
                printlist.append(
                    '{} {} {:^14} {:^14} {} {:^6} {:^9}'.format(adjust_for_chinese(i['medal_name'] + '|' + str(i['level'])),
                                                           adjust_for_chinese(i['anchorInfo']['uname']),
                                                           str(i['intimacy']) + '/' + str(i['next_intimacy']),
                                                           str(i['todayFeed']) + '/' + str(i['dayLimit']),
                                                           adjust_for_chinese(str(i['rank'])),
                                                           dic_worn[str(i['status'])], i['roomid']))
        if show:
            printer.info(printlist, True)
        if list_wanted_medal:
            list_return_medal = []
            for roomid in list_wanted_medal:
                for i in list_medal:
                    if i[0] == roomid:
                        list_return_medal.append(i[:3])
                        break
        else:
            list_return_medal = [i[:3] for i in sorted(list_medal, key=itemgetter(3), reverse=True)]
        return list_return_medal
```

**Comment by a253208088** [comment]
改了 运行后没变化 怎么打印json

**Comment by a253208088** [comment]
是不是
{'code': 0, 'msg': '', 'message': '', 'data': {'medalCount': 20, 'count': 19, 'fansMedalList': [{'id': '262094', 'uid': 174871, 'target_id': 597396, 'medal_id': 1, 'score': 397297, 'level': 18, 'intimacy': 147396, 'next_intimacy': 250000, 'status': 1, 'source': 1, 'receive_channel': 1, 'is_receive': 1, 'master_status': 1, 'receive_time': '2016-10-18 09:54:26', 'mtime': '2018-08-04 20:24:05', 'ctime': '2016-10-18 09:54:26', 'reserve1': '0', 'reserve2': '', 'today_intimacy': 0, 'medal_name': '猫耳', 'master_available': '1', 'target_name': '猫耳爱丽丝', 'target_face': 'https://i0.hdslb.com/bfs/face/6e67e3ef393bf454a2944103910a26518e51d43d.jpg', 'rank': 25, 'medal_color': 16752445, 'today_feed': 2000, 'guard_type': 0, 'day_limit': 2000, 'todayFeed': 2000, 'dayLimit': 2000, 'uname': '猫耳爱丽丝', 'color': 16752445, 'medalName': '猫耳', 'guard_level': 0, 'guard_medal_title': '未开启加成', 'anchorInfo': {'uid': 597396, 'uname': '猫耳爱丽丝', 'face': 'https://i0.hdslb.com/bfs/face/6e67e3ef393bf454a2944103910a26518e51d43d.jpg', 'rank': '10000', 'platform_user_level': 6, 'mobile_verify': 0, 'official_verify': {'type': -1, 'desc': '', 'role': 0}, 'vip_type': 2}, 'roomid': 133}, {'id': '568145', 'uid': 174871, 'target_id': 9617619, 'medal_id': 7, 'score': 10809, 'level': 10, 'intimacy': 1408, 'next_intimacy': 5500, 'status': 0, 'source': 1, 'receive_channel': 1, 'is_receive': 1, 'master_status': 1, 'receive_time': '2017-04-30 15:22:55', 'mtime': '2018-08-04 10:37:14', 'ctime': '2017-04-30 15:22:55', 'reserve1': '0', 'reserve2': '', 'today_intimacy': 0, 'medal_name': '欧皇', 'master_available': '1', 'target_name': '哔哩哔哩直播', 'target_face': 'https://i2.hdslb.com/bfs/face/58ca83240e58c3e6ce1ebb9828ce84f6f1b72863.jpg', 'rank': 501, 'medal_color': 10512625, 'today_feed': 0, 'guard_type': 0, 'day_limit': 1000, 'todayFeed': 0, 'dayLimit': 1000, 'uname': '哔哩哔哩直播', 'color': 10512625, 'medalName': '欧皇', 'guard_level': 0, 'guard_medal_title': '未开启加成', 'anchorInfo': {'uid': 9617619, 'uname': '哔哩哔哩直播', 'face': 'https://i2.hdslb.com/bfs/face/58ca83240e58c3e6ce1ebb9828ce84f6f1b72863.jpg', 'rank': '10000', 'platform_user_level': 6, 'mobile_verify': 0, 'official_verify': {'type': 1, 'desc': 'bilibili直播 官方账号', 'role': 3}, 'vip_type': 0}, 'roomid': 1}, {'id': '550054', 'uid': 174871, 'target_id': 592761, 'medal_id': 47, 'score': 1350, 'level': 4, 'intimacy': 349, 'next_intimacy': 700, 'status': 0, 'source': 1, 'receive_channel': 1, 'is_receive': 1, 'master_status': 0, 'receive_time': '2017-04-13 11:57:58', 'mtime': '2018-08-04 10:37:14', 'ctime': '2017-04-13 11:57:58', 'reserve1': '0', 'reserve2': '', 'today_intimacy': 0, 'medal_name': '可樂', 'master_available': '1', 'target_name': '可樂C', 'target_face': 'https://i1.hdslb.com/bfs/face/0aec19109c04808e28222d18cd3aa7bf3c919629.jpg', 'rank': 5721, 'medal_color': 6406234, 'today_feed': 0, 'guard_type': 0, 'day_limit': 500, 'todayFeed': 0, 'dayLimit': 500, 'uname': '可樂C', 'color': 6406234, 'medalName': '可樂', 'guard_level': 0, 'guard_medal_title': '未开启加成', 'anchorInfo': {'uid': 592761, 'uname': '可樂C', 'face': 'https://i1.hdslb.com/bfs/face/0aec19109c04808e28222d18cd3aa7bf3c919629.jpg', 'rank': '10000', 'platform_user_level': 6, 'mobile_verify': 0, 'official_verify': {'type': 0, 'desc': '2015夏夜鬼畜大赏第三名', 'role': 2}, 'vip_type': 1}, 'roomid': 114}, {'id': '540684', 'uid': 174871, 'target_id': 682508, 'medal_id': 67, 'score': 1350, 'level': 4, 'intimacy': 349, 'next_intimacy': 700, 'status': 0, 'source': 1, 'receive_channel': 1, 'is_receive': 1, 'master_status': 0, 'receive_time': '2017-04-03 11:46:14', 'mtime': '2018-08-04 10:37:14', 'ctime': '2017-04-03 11:46:14', 'reserve1': '0', 'reserve2': '', 'today_intimacy': 0, 'medal_name': '十六', 'master_available': '1', 'target_name': '超心塞的十六', 'target_face': 'https://i1.hdslb.com/bfs/face/a42f5bf0c5a1db51f520b9e86fd646378f917867.jpg', 'rank': 10077, 'medal_color': 6406234, 'today_feed': 0, 'guard_type': 0, 'day_limit': 500, 'todayFeed': 0, 'dayLimit': 500, 'uname': '超心塞的十六', 'color': 6406234, 'medalName': '十六', 'guard_level': 0, 'guard_medal_title': '未开启加成', 'anchorInfo': {'uid': 682508, 'uname': '超心塞的十六', 'face': 'https://i1.hdslb.com/bfs/face/a42f5bf0c5a1db51f520b9e86fd646378f917867.jpg', 'rank': '10000', 'platform_user_level': 6, 'mobile_verify': 0, 'official_verify': {'type': 0, 'desc': 'bilibili直播签约主播', 'role': 2}, 'vip_type': 2}, 'roomid': 148}, {'id': '824159', 'uid': 174871, 'target_id': 15553263, 'medal_id': 108, 'score': 10711, 'level': 10, 'intimacy': 1310, 'next_intimacy': 5500, 'status': 0, 'source': 1, 'receive_channel': 1, 'is_receive': 1, 'master_status': 1, 'receive_time': '2017-08-28 00:14:58', 'mtime': '2018-08-04 10:37:14', 'ctime': '2017-08-28 00:14:58', 'reserve1': '0', 'reserve2': '', 'today_intimacy': 0, 'medal_name': '麻麻', 'master_available': '1', 'target_name': ' 元气少女麻麻', 'target_face': 'https://i0.hdslb.com/bfs/face/181e59af16f1c5cfee7d0b5b7ca29e4170e939bd.jpg', 'rank': 637, 'medal_color': 10512625, 'today_feed': 0, 'guard_type': 0, 'day_limit': 1000, 'todayFeed': 0, 'dayLimit': 1000, 'uname': '元气少女麻麻', 'color': 10512625, 'medalName': '麻麻', 'guard_level': 0, 'guard_medal_title': '未开启加成', 'anchorInfo': {'uid': 15553263, 'uname': '元气少女麻麻', 'face': 'https://i0.hdslb.com/bfs/face/181e59af16f1c5cfee7d0b5b7ca29e4170e939bd.jpg', 'rank': '10000', 'platform_user_level': 6, 'mobile_verify': 0, 'official_verify': {'type': 0, 'desc': 'bilibili直播签约主播\r\n', 'role': 2}, 'vip_type': 2}, 'roomid': 125}, {'id': '569660', 'uid': 174871, 'target_id': 7129848, 'medal_id': 122, 'score': 1310, 'level': 4, 'intimacy': 309, 'next_intimacy': 700, 'status': 0, 'source': 1, 'receive_channel': 1, 'is_receive': 1, 'master_status': 0, 'receive_time': '2017-05-01 11:42:04', 'mtime': '2018-08-04 10:37:14', 'ctime': '2017-05-01 11:42:04', 'reserve1': '0', 'reserve2': '', 'today_intimacy': 0, 'medal_name': '酋长', 'master_available': '1', 'target_name': 'bilibili相簿', 'target_face': 'https://i1.hdslb.com/bfs/face/084bd13eb5dc51a64674085bb28e958ecd5addd0.jpg', 'rank': 256, 'medal_color': 6406234, 'today_feed': 0, 'guard_type': 0, 'day_limit': 500, 'todayFeed': 0, 'dayLimit': 500, 'uname': 'bilibili相簿', 'color': 6406234, 'medalName': '酋长', 'guard_level': 0, 'guard_medal_title': '未开启加成', 'anchorInfo': {'uid': 7129848, 'uname': 'bilibili相簿', 'face': 'https://i1.hdslb.com/bfs/face/084bd13eb5dc51a64674085bb28e958ecd5addd0.jpg', 'rank': '10000', 'platform_user_level': 3, 'mobile_verify': 0, 'official_verify': {'type': 1, 'desc': 'bilibili相簿 官方帐号', 'role': 3}, 'vip_type': 0}, 'roomid': 2}, {'id': '1035106', 'uid': 174871, 'target_id': 893213, 'medal_id': 131, 'score': 10806, 'level': 10, 'intimacy': 1405, 'next_intimacy': 5500, 'status': 0, 'source': 1, 'receive_channel': 1, 'is_receive': 1, 'master_status': 0, 'receive_time': '2017-12-14 00:55:05', 'mtime': '2018-08-04 10:37:14', 'ctime': '2017-12-14 00:55:05', 'reserve1': '0', 'reserve2': '', 'today_intimacy': 0, 'medal_name': '初音', 'master_available': '1', 'target_name': 'MU秋日', 'target_face': 'https://i2.hdslb.com/bfs/face/33213b52371a39e7abd309997d6c75467a4b4972.jpg', 'rank': 397, 'medal_color': 10512625, 'today_feed': 0, 'guard_type': 0, 'day_limit': 1000, 'todayFeed': 0, 'dayLimit': 1000, 'uname': 'MU秋日', 'color': 10512625, 'medalName': '初音', 'guard_level': 0, 'guard_medal_title': '未开启加成', 'anchorInfo': {'uid': 893213, 'uname': 'MU秋日', 'face': 'https://i2.hdslb.com/bfs/face/33213b52371a39e7abd309997d6c75467a4b4972.jpg', 'rank': '10000', 'identification': 1, 'mobile_verify': 1, 'platform_user_level': 6, 'vip_type': 2, 'official_verify': {'type': -1, 'desc': '', 'role': 0}}, 'roomid': 113}, {'id': '540134', 'uid': 174871, 'target_id': 837019, 'medal_id': 171, 'score': 1657, 'level': 4, 'intimacy': 656, 'next_intimacy': 700, 'status': 0, 'source': 1, 'receive_channel': 1, 'is_receive': 1, 'master_status': 1, 'receive_time': '2017-04-02 21:52:15', 'mtime': '2018-08-04 10:37:14', 'ctime': '2017-04-02 21:52:15', 'reserve1': '0', 'reserve2': '', 'today_intimacy': 0, 'medal_name': '提督', 'master_available': '1', 'target_name': '猫耳金剛改二', 'target_face': 'https://i1.hdslb.com/bfs/face/5242b977f222d6320b52dc93be3d47b6bc71706b.jpg', 'rank': 1000, 'medal_color': 6406234, 'today_feed': 0, 'guard_type': 0, 'day_limit': 500, 'todayFeed': 0, 'dayLimit': 500, 'uname': '猫耳金剛改二', 'color': 6406234, 'medalName': '提督', 'guard_level': 0, 'guard_medal_title': '未开启加成', 'anchorInfo': {'uid': 837019, 'uname': '猫耳金剛改二', 'face': 'https://i1.hdslb.com/bfs/face/5242b977f222d6320b52dc93be3d47b6bc71706b.jpg', 'rank': '10000', 'platform_user_level': 5, 'mobile_verify': 0, 'official_verify': {'type': -1, 'desc': '', 'role': 0}, 'vip_type': 2}, 'roomid': 169}, {'id': '437875', 'uid': 174871, 'target_id': 232150, 'medal_id': 337, 'score': 1360, 'level': 4, 'intimacy': 359, 'next_intimacy': 700, 'status': 0, 'source': 1, 'receive_channel': 1, 'is_receive': 1, 'master_status': 0, 'receive_time': '2017-03-06 10:40:50', 'mtime': '2018-08-04 10:37:14', 'ctime': '2017-03-06 10:40:50', 'reserve1': '0', 'reserve2': '', 'today_intimacy': 0, 'medal_name': '下限', 'master_available': '1', 'target_name': '下限酱Orz', 'target_face': 'https://i0.hdslb.com/bfs/face/51402437ff06fb798835a966ce9c0896620ffb57.jpg', 'rank': 5274, 'medal_color': 6406234, 'today_feed': 0, 'guard_type': 0, 'day_limit': 500, 'todayFeed': 0, 'dayLimit': 500, 'uname': '下限酱Orz', 'color': 6406234, 'medalName': '下限', 'guard_level': 0, 'guard_medal_title': '未开启加成', 'anchorInfo': {'uid': 232150, 'uname': '下限酱Orz', 'face': 'https://i0.hdslb.com/bfs/face/51402437ff06fb798835a966ce9c0896620ffb57.jpg', 'rank': '10000', 'identification': 1, 'mobile_verify': 1, 'platform_user_level': 5, 'vip_type': 0, 'official_verify': {'type': -1, 'desc': '', 'role': 0}}, 'roomid': 149}, {'id': '966034', 'uid': 174871, 'target_id': 277257, 'medal_id': 474, 'score': 1518, 'level': 4, 'intimacy': 517, 'next_intimacy': 700, 'status': 0, 'source': 2, 'receive_channel': 2, 'is_receive': 1, 'master_status': 1, 'receive_time': '2017-11-11 07:34:16', 'mtime': '2018-08-04 10:37:14', 'ctime': '2017-11-11 07:26:39', 'reserve1': '0', 'reserve2': '', 'today_intimacy': 0, 'medal_name': 'MIKU', 'master_available': '1', 'target_name': '初音社', 'target_face': 'https://i1.hdslb.com/bfs/face/936b433f7342ce55f2833b519756bcf255b4dfa1.jpg', 'rank': 440, 'medal_color': 6406234, 'today_feed': 0, 'guard_type': 0, 'day_limit': 500, 'todayFeed': 0, 'dayLimit': 500, 'uname': '初音社', 'color': 6406234, 'medalName': 'MIKU', 'guard_level': 0, 'guard_medal_title': '未开启加成', 'anchorInfo': {'uid': 277257, 'uname': '初音社', 'face': 'https://i1.hdslb.com/bfs/face/936b433f7342ce55f2833b519756bcf255b4dfa1.jpg', 'rank': '10000', 'identification': 1, 'mobile_verify': 1, 'platform_user_level': 6, 'vip_type': 2, 'official_verify': {'type': 0, 'desc': 'bilibili 知名UP主', 'role': 1}}, 'roomid': 44451}, {'id': '547650', 'uid': 174871, 'target_id': 14546523, 'medal_id': 2079, 'score': 10751, 'level': 10, 'intimacy': 1350, 'next_intimacy': 5500, 'status': 0, 'source': 1, 'receive_channel': 1, 'is_receive': 1, 'master_status': 0, 'receive_time': '2017-04-10 10:33:03', 'mtime': '2018-08-04 10:37:14', 'ctime': '2017-04-10 10:33:03', 'reserve1': '0', 'reserve2': '', 'today_intimacy': 0, 'medal_name': '巡音', 'master_available': '1', 'target_name': 'MU巡音', 'target_face': 'https://i2.hdslb.com/bfs/face/36147858645293be2bc1a6dd10567b5bff2ae6f6.jpg', 'rank': 35, 'medal_color': 10512625, 'today_feed': 0, 'guard_type': 0, 'day_limit': 1000, 'todayFeed': 0, 'dayLimit': 1000, 'uname': 'MU巡音', 'color': 10512625, 'medalName': '巡音', 'guard_level': 0, 'guard_medal_title': '未开启加成', 'anchorInfo': {'uid': 14546523, 'uname': 'MU巡音', 'face': 'https://i2.hdslb.com/bfs/face/36147858645293be2bc1a6dd10567b5bff2ae6f6.jpg', 'rank': '10000', 'platform_user_level': 2, 'mobile_verify': 0, 'official_verify': {'type': -1, 'desc': '', 'role': 0}, 'vip_type': 0}, 'roomid': 37067}, {'id': '542893', 'uid': 174871, 'target_id': 4454981, 'medal_id': 2178, 'score': 1360, 'level': 4, 'intimacy': 359, 'next_intimacy': 700, 'status': 0, 'source': 1, 'receive_channel': 1, 'is_receive': 1, 'master_status': 0, 'receive_time': '2017-04-05 11:38:30', 'mtime': '2018-08-04 10:37:14', 'ctime': '2017-04-05 11:38:30', 'reserve1': '0', 'reserve2': '', 'today_intimacy': 0, 'medal_name': '祈愿', 'master_available': '1', 'target_name': '我丶好期待', 'target_face': 'https://i2.hdslb.com/bfs/face/48e49865e68124909dad37d61d71ea1c2a3891f2.jpg', 'rank': 6415, 'medal_color': 6406234, 'today_feed': 0, 'guard_type': 0, 'day_limit': 500, 'todayFeed': 0, 'dayLimit': 500, 'uname': '我丶好期待', 'color': 6406234, 'medalName': '祈愿', 'guard_level': 0, 'guard_medal_title': '未开启加成', 'anchorInfo': {'uid': 4454981, 'uname': ' 我丶好期待', 'face': 'https://i2.hdslb.com/bfs/face/48e49865e68124909dad37d61d71ea1c2a3891f2.jpg', 'rank': '10000', 'platform_user_level': 6, 'mobile_verify': 0, 'official_verify': {'type': 0, 'desc': 'bilibili 知名UP主', 'role': 1}, 'vip_type': 2}, 'roomid': 157901}, {'id': '545331', 'uid': 174871, 'target_id': 488349, 'medal_id': 2538, 'score': 1340, 'level': 4, 'intimacy': 339, 'next_intimacy': 700, 'status': 0, 'source': 1, 'receive_channel': 1, 'is_receive': 1, 'master_status': 0, 'receive_time': '2017-04-08 11:37:50', 'mtime': '2018-08-04 10:37:14', 'ctime': '2017-04-08 11:37:50', 'reserve1': '0', 'reserve2': '', 'today_intimacy': 0, 'medal_name': '凜喵', 'master_available': '1', 'target_name': '三笠の大 小姐凜喵', 'target_face': 'https://i2.hdslb.com/bfs/face/8eda997cd5f10f164f3ceb73d3f83b529cdd5edc.jpg', 'rank': 37, 'medal_color': 6406234, 'today_feed': 0, 'guard_type': 0, 'day_limit': 500, 'todayFeed': 0, 'dayLimit': 500, 'uname': '三笠 の大小姐凜喵', 'color': 6406234, 'medalName': '凜喵', 'guard_level': 0, 'guard_medal_title': '未开启加成', 'anchorInfo': {'uid': 488349, 'uname': '三笠の大小姐凜喵', 'face': 'https://i2.hdslb.com/bfs/face/8eda997cd5f10f164f3ceb73d3f83b529cdd5edc.jpg', 'rank': '10000', 'platform_user_level': 5, 'mobile_verify': 0, 'official_verify': {'type': -1, 'desc': '', 'role': 0}, 'vip_type': 2}, 'roomid': 191377}, {'id': '337538', 'uid': 174871, 'target_id': 7293084, 'medal_id': 5648, 'score': 10711, 'level': 10, 'intimacy': 1310, 'next_intimacy': 5500, 'status': 0, 'source': 1, 'receive_channel': 1, 'is_receive': 1, 'master_status': 1, 'receive_time': '2017-01-01 00:41:28', 'mtime': '2018-08-04 10:37:14', 'ctime': '2017-01-01 00:41:28', 'reserve1': '0', 'reserve2': '', 'today_intimacy': 0, 'medal_name': '猫', 'master_available': '1', 'target_name': '猫耳小爱', 'target_face': 'https://i2.hdslb.com/bfs/face/0220d137b340b3bc2f6836c2166d7455294f3018.jpg', 'rank': 24, 'medal_color': 10512625, 'today_feed': 0, 'guard_type': 0, 'day_limit': 1000, 'todayFeed': 0, 'dayLimit': 1000, 'uname': '猫耳小爱', 'color': 10512625, 'medalName': '猫', 'guard_level': 0, 'guard_medal_title': '未开启加成', 'anchorInfo': {'uid': 7293084, 'uname': '猫耳小爱', 'face': 'https://i2.hdslb.com/bfs/face/0220d137b340b3bc2f6836c2166d7455294f3018.jpg', 'rank': '10000', 'identification': 1, 'mobile_verify': 1, 'platform_user_level': 3, 'vip_type': 0, 'official_verify': {'type': -1, 'desc': '', 'role': 0}}, 'roomid': 562418}, {'id': '783520', 'uid': 174871, 'target_id': 3125954, 'medal_id': 5803, 'score': 11729, 'level': 10, 'intimacy': 2328, 'next_intimacy': 5500, 'status': 0, 'source': 1, 'receive_channel': 1, 'is_receive': 1, 'master_status': 1, 'receive_time': '2017-08-10 20:13:08', 'mtime': '2018-08-04 10:37:14', 'ctime': '2017-08-10 20:13:08', 'reserve1': '0', 'reserve2': '', 'today_intimacy': 0, 'medal_name': '夫人', 'master_available': '1', 'target_name': '松羊夫人', 'target_face': 'https://i1.hdslb.com/bfs/face/69841313937c70c722d85c777e5bd51dd5736d03.jpg', 'rank': 686, 'medal_color': 10512625, 'today_feed': 0, 'guard_type': 0, 'day_limit': 1000, 'todayFeed': 0, 'dayLimit': 1000, 'uname': '松羊夫人', 'color': 10512625, 'medalName': '夫人', 'guard_level': 0, 'guard_medal_title': '未开启加成', 'anchorInfo': {'uid': 3125954, 'uname': '松羊夫人', 'face': 'https://i1.hdslb.com/bfs/face/69841313937c70c722d85c777e5bd51dd5736d03.jpg', 'rank': '10000', 'platform_user_level': 5, 'mobile_verify': 0, 'official_verify': {'type': 0, 'desc': 'bilibili 知名UP主', 'role': 1}, 'vip_type': 2}, 'roomid': 366}, {'id': '652662', 'uid': 174871, 'target_id': 2337891, 'medal_id': 13786, 'score': 11891, 'level': 10, 'intimacy': 2490, 'next_intimacy': 5500, 'status': 0, 'source': 3, 'receive_channel': 2, 'is_receive': 1, 'master_status': 1, 'receive_time': '2017-07-30 17:11:30', 'mtime': '2018-08-04 10:37:14', 'ctime': '2017-06-30 09:13:25', 'reserve1': '0', 'reserve2': '', 'today_intimacy': 0, 'medal_name': ' 乐哥', 'master_available': '1', 'target_name': '乐歌', 'target_face': 'https://i2.hdslb.com/bfs/face/17d00108c3cb75210eaaa9bae3b755553e13880c.jpg', 'rank': 10, 'medal_color': 10512625, 'today_feed': 0, 'guard_type': 0, 'day_limit': 1000, 'todayFeed': 0, 'dayLimit': 1000, 'uname': '乐歌', 'color': 10512625, 'medalName': '乐哥', 'guard_level': 0, 'guard_medal_title': '未开启加成', 'anchorInfo': {'uid': 2337891, 'uname': '乐歌', 'face': 'https://i2.hdslb.com/bfs/face/17d00108c3cb75210eaaa9bae3b755553e13880c.jpg', 'rank': '10000', 'identification': 1, 'mobile_verify': 1, 'platform_user_level': 6, 'vip_type': 2, 'official_verify': {'type': 0, 'desc': 'bilibili 知名UP主', 'role': 1}}, 'roomid': 80588}, {'id': '611608', 'uid': 174871, 'target_id': 2937475, 'medal_id': 18527, 'score': 12067, 'level': 10, 'intimacy': 2666, 'next_intimacy': 5500, 'status': 0, 'source': 1, 'receive_channel': 1, 'is_receive': 1, 'master_status': 1, 'receive_time': '2017-05-31 16:32:05', 'mtime': '2018-08-04 10:37:14', 'ctime': '2017-05-31 16:32:05', 'reserve1': '0', 'reserve2': '', 'today_intimacy': 0, 'medal_name': '真姬酱', 'master_available': '1', 'target_name': '可愛小羊毛', 'target_face': 'https://i0.hdslb.com/bfs/face/2e4d42c630d6715250fa5d9b212bdcec36299cb0.jpg', 'rank': 37, 'medal_color': 10512625, 'today_feed': 0, 'guard_type': 0, 'day_limit': 1000, 'todayFeed': 0, 'dayLimit': 1000, 'uname': '可愛小羊毛', 'color': 10512625, 'medalName': '真姬酱', 'guard_level': 0, 'guard_medal_title': '未开启加成', 'anchorInfo': {'uid': 2937475, 'uname': '可愛小羊毛', 'face': 'https://i0.hdslb.com/bfs/face/2e4d42c630d6715250fa5d9b212bdcec36299cb0.jpg', 'rank': '10000', 'platform_user_level': 6, 'mobile_verify': 0, 'official_verify': {'type': -1, 'desc': '', 'role': 0}, 'vip_type': 1}, 'roomid': 917825}, {'id': '621991', 'uid': 174871, 'target_id': 12695676, 'medal_id': 22740, 'score': 12438, 'level': 10, 'intimacy': 3037, 'next_intimacy': 5500, 'status': 0, 'source': 1, 'receive_channel': 1, 'is_receive': 1, 'master_status': 1, 'receive_time': '2017-06-09 17:46:47', 'mtime': '2018-08-04 20:24:05', 'ctime': '2017-06-09 17:46:47', 'reserve1': '0', 'reserve2': '', 'today_intimacy': 0, 'medal_name': '蠢蚁蚁', 'master_available': '1', 'target_name': '可爱大蚂蚁', 'target_face': 'https://i1.hdslb.com/bfs/face/dba1e8df0d68c9ba70b329de486e81ed20322777.jpg', 'rank': 230, 'medal_color': 10512625, 'today_feed': 0, 'guard_type': 0, 'day_limit': 1000, 'todayFeed': 0, 'dayLimit': 1000, 'uname': '可爱大蚂蚁', 'color': 10512625, 'medalName': '蠢蚁蚁', 'guard_level': 0, 'guard_medal_title': '未开启加成', 'anchorInfo': {'uid': 12695676, 'uname': '可爱大蚂蚁', 'face': 'https://i1.hdslb.com/bfs/face/dba1e8df0d68c9ba70b329de486e81ed20322777.jpg', 'rank': '10000', 'platform_user_level': 6, 'mobile_verify': 0, 'official_verify': {'type': -1, 'desc': '', 'role': 0}, 'vip_type': 2}, 'roomid': 3749977}, {'id': '936165', 'uid': 174871, 'target_id': 35954237, 'medal_id': 28915, 'score': 1479, 'level': 4, 'intimacy': 478, 'next_intimacy': 700, 'status': 0, 'source': 2, 'receive_channel': 2, 'is_receive': 1, 'master_status': 0, 'receive_time': '2017-10-26 15:54:06', 'mtime': '2018-08-04 10:37:14', 'ctime': '2017-10-26 07:42:22', 'reserve1': '0', 'reserve2': '', 'today_intimacy': 0, 'medal_name': '真夕', 'master_available': '1', 'target_name': '星野真夕', 'target_face': 'https://i0.hdslb.com/bfs/face/931d19ced6db831a7f4314b56ee5c6020c7d3ff9.jpg', 'rank': 11, 'medal_color': 6406234, 'today_feed': 0, 'guard_type': 0, 'day_limit': 500, 'todayFeed': 0, 'dayLimit': 500, 'uname': '星野真夕', 'color': 6406234, 'medalName': '真夕', 'guard_level': 0, 'guard_medal_title': '未开启加成', 'anchorInfo': {'uid': 35954237, 'uname': ' 星野真夕', 'face': 'https://i0.hdslb.com/bfs/face/931d19ced6db831a7f4314b56ee5c6020c7d3ff9.jpg', 'rank': '10000', 'platform_user_level': 6, 'mobile_verify': 0, 'official_verify': {'type': 0, 'desc': 'bilibili 知名UP主', 'role': 1}, 'vip_type': 2}}], 'name': '****', 'pageinfo': {'totalpages': 1, 'curPage': 1}}}
Task exception was never retrieved
future: <Task finished coro=<auto_send_gift() done, defined at E:\bilibili-live-tools-master\Tasks.py:97> exception=KeyError('roomid',)>
Traceback (most recent call last):
  File "E:\bilibili-live-tools-master\Tasks.py", line 107, in auto_send_gift
    list_medal += await utils.fetch_medal(False, ConfigLoader().dic_user['task_control']['send2medal'])
  File "E:\bilibili-live-tools-master\utils.py", line 79, in fetch_medal
    list_medal.append((i['roomid'], int(i['dayLimit']) - int(i['todayFeed']), i['medal_name'], i['level']))
KeyError: 'roomid'

**Comment by yjqiang** [comment]
你这个json炸了我电脑，找到bug了，就是被封禁了

**Comment by a253208088** [comment]
我手动都可以投辣条啊

**Comment by yjqiang** [comment]
星野真夕 这人的房间被封了

**Comment by a253208088** [comment]
谢谢了  删了真夕勋章  恢复正常了

**Comment by yjqiang** [comment]
目前已经增加了这个问题的忽略
