### ISSUE TITLE
请教一点问题

### ISSUE THREAD

**Issue by naganai** [yjqiang/bilibili-live-tools#87]
向https://passport.bilibili.com/api/oauth2/getKey请求数据时，为什么appkey和sign变量一定要格式化后能请求到数据，直接拼成字符串不行吗？有点搞不懂什么机制，字符串看起来都一样。
        还有配置文件里appkey这个变量的值是怎么取得的，在登录页面各种请求里面找的？听说要到联系客服申请，这也太严格了吧。
        顺便要个联系方式，B站UID什么的以后方便提问题，我是个python小白，还请作者多多指教。
见:bilibili.py
    request_getkey
    calc_sign

**Comment by yjqiang** [comment]
sign的目的是为了对某段str进行签名，b站对app的api要求必须签名，否则认为非法。
appkey的获取随便下载app，抓包就能得到，不用听客服瞎咧咧。
