### ISSUE TITLE
提督和舰长也有亲密度啦

### ISSUE THREAD

**Issue by LeecGitHub** [yjqiang/bilibili-live-tools#88]
最新app端可以获取（有领取时间限制）
https://api.live.bilibili.com/lottery/v1/Lottery/check_guard?roomid=11519517&tdsourcetag=s_pcqq_aiomsg
另小声bb：大佬能不能发一个多用户版本的exe文件，小白不会用

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bilibili-live-tools/commit/bd17e7760ce10961638e333da30984fbaa0f065a
目前问题是不是广播

**Comment by yjqiang** [comment]
exe我没弄过。。。
