### ISSUE TITLE
送亲密度礼物  参数错误535

### ISSUE THREAD

**Issue by scott90578** [yjqiang/bilibili-live-tools#89]
![1](https://user-images.githubusercontent.com/24499006/44788235-15aae700-abcc-11e8-8431-a61dd686be6e.jpg)

**Comment by yjqiang** [comment]
最新版加入了debug信息

**Comment by scott90578** [comment]
![20180901220621](https://user-images.githubusercontent.com/24499006/44946678-4ccf0180-ae33-11e8-9bfe-242aa5fdb496.png)
