### ISSUE TITLE
网页端活动抽奖  循环 

### ISSUE THREAD

**Issue by scott90578** [yjqiang/bilibili-live-tools#91]
![tim 20180901231949](https://user-images.githubusercontent.com/24499006/44947285-8ad12300-ae3d-11e8-882b-48d0ca69d741.png)
![tim 20180901231950](https://user-images.githubusercontent.com/24499006/44947296-c23fcf80-ae3d-11e8-83da-94077ab7e712.png)

**Comment by yjqiang** [comment]
这是v4，b站自己有一些延迟的原因

**Comment by lovezm** [comment]
对了  舰长提督是怎样监听的 貌似并不多啊  按理来说应该很多的

**Comment by yjqiang** [comment]
请另开issue

**Comment by lovezm** [comment]
![image](https://user-images.githubusercontent.com/10624938/54737578-b7873500-4beb-11e9-9e1f-2c90fcf5462d.png)
昨天开始会无限循环了 然后就403

**Comment by yjqiang** [comment]
> ![image](https://user-images.githubusercontent.com/10624938/54737578-b7873500-4beb-11e9-9e1f-2c90fcf5462d.png)
> 昨天开始会无限循环了 然后就403

方便的话看看是什么问题，是暂时性api错误还是怎么着，目前我同时是两个版本，这是v4，bili2.0采用了老版v3，讲道理不应该啊。。。

**Comment by lovezm** [comment]
监控到抽奖以后 就会这样  然后一段时间就403了

**Comment by lovezm** [comment]
没有出现api错误等log

**Comment by lovezm** [comment]
顺便问一下  输入账号密码后[WinError 10061] 由于目标计算机积极拒绝，无法连接是为啥

**Comment by yjqiang** [comment]
> 顺便问一下 输入账号密码后[WinError 10061] 由于目标计算机积极拒绝，无法连接是为啥 防火墙啥的都关了

积极拒绝肯定是本地网络问题，这个复杂很多，你看看代理之类的吧。

**Comment by yjqiang** [comment]
我觉得没什么必要循环了，新版的加入了https://github.com/yjqiang/bili2.0/blob/master/json_rsp_ctrl.py ，这样异常的东西直接过滤掉。
