### ISSUE TITLE
应援团签到

### ISSUE THREAD

**Issue by CharlesLiu7** [yjqiang/bilibili-live-tools#92]
问题：脚本在首次运行的时候会检测应援团签到，签到并领取亲密度后，第二天再检查应援团签到时会**直接显示应援团已签到**。我终止脚本并且重新运行后，应援团会显示未签到并且签到领取亲密度。

**Comment by yjqiang** [comment]
签到间隔大约是24h，所以可能正好碰上了间隔，这个确定不会有bug
