### ISSUE TITLE
被matplotlib 搞懵逼了

### ISSUE THREAD

**Issue by zuosc** [yjqiang/bilibili-live-tools#96]
尝试加一个dockerfile   结果matplotlib死活出错。

**Comment by zuosc** [comment]
@yjqiang   不是这个问题。  是在构建docker镜像的时候，matplotlib的安装是需要编译的，然后各种编译缺失、失败。  搞了好久。。。。

**Comment by yjqiang** [comment]
不爽那个webcolors……

**Comment by yjqiang** [comment]
那货写得过烂

**Comment by zuosc** [comment]
@yjqiang   。。。我在尝试构建一下吧。。。心累

**Comment by zuosc** [comment]
@yjqiang   终于搞定了。。。。原来是我的VPS性能不足。。。编译编译就崩溃了。。。

用我的Mac book pro 都构建了十几分钟。。。。


这波真的强。。。

**Comment by yjqiang** [comment]
gg
